name: osm_flutter

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image:  python:3
      #image:  google/dart:latest
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - uses: britannio/action-install-flutter@v1
      - run: dart --version
      - name: Install Flutter SDK
        uses: mobiledevops/flutter-sdk-action@v1.0.0
      - run: flutter --version
      - name: Setup credentials
        run: |
          mkdir -p ~/.pub-cache
          cat <<EOF > ~/.pub-cache/credentials.json
          {
            "accessToken":"${{ secrets.OAUTH_ACCESS_TOKEN }}",
            "refreshToken":"${{ secrets.OAUTH_REFRESH_TOKEN }}",
            "tokenEndpoint":"https://accounts.google.com/o/oauth2/token",
            "scopes":["https://www.googleapis.com/auth/userinfo.email","openid"],
            "expiration": ${{ secrets.EXP }}
          }
          EOF
      - name: preparation release
        run: python check_pubspec_release.py
      - name: clear before release
        run: |
          rm -f *.gif
          rm -rf assets
          rm -rf flutter_osm_interface
          rm -rf flutter_osm_web
          rm -f check_pubspec_release.py
      - name: fomarting files
        run : dart format .
      - name: Publish package
        run:  flutter pub publish -f