name: osm_flutter

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image:  python:3
      #image:  google/dart:latest
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - uses: dart-lang/setup-dart@v1
      - name: Install Flutter SDK
        uses: britannio/action-install-flutter@v1
      - run: dart --version
      - run: flutter --version
      - name: Setup credentials
        run: |
          mkdir -p ~/.pub-cache
          cat <<EOF > ~/.pub-cache/credentials.json
          {
            "accessToken":"${{ secrets.OAUTH_ACCESS_TOKEN }}",
            "refreshToken":"${{ secrets.OAUTH_REFRESH_TOKEN }}",
            "tokenEndpoint":"https://accounts.google.com/o/oauth2/token",
            "scopes":["https://www.googleapis.com/auth/userinfo.email","openid"],
            "expiration": ${{ secrets.EXP }}
          }
          EOF
      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.6.0 @actions/http-client
      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        with:
         script: |
           const coreActions = require('@actions/core')
           let id_token = await coreActions.getIDToken('https://pub.dev')
           coreActions.setOutput('PUB_TOKEN', id_token)
           echo "${PUB_TOKEN}"
      - name: preparation release
        run: python check_pubspec_release.py
      - name: clear before release
        run: |
          rm -f *.gif
          rm -rf assets
          rm -rf flutter_osm_interface
          rm -rf flutter_osm_web
          rm -f check_pubspec_release.py
      - name: fomarting files
        run : dart format .
      - name: Publish package
        run:  flutter pub publish -f